#pragma once
#define CREATE_USERS_TABLE "CREATE TABLE IF NOT EXISTS USERS (USER_ID INTEGER PRIMARY KEY AUTOINCREMENT, USERNAME TEXT NOT NULL UNIQUE, SCORE INTEGER DEFAULT 0);"
#define ADD_NEW_USER "INSERT INTO USERS (USERNAME, SCORE) VALUES (?, ?);"
#define DELETE_EXISTING_USER "DELETE FROM USERS WHERE USERNAME = ?;"
#define UPDATE_PLAYER_SCORE "UPDATE USERS SET SCORE = SCORE + ? WHERE USERNAME = ?;"
#define GET_ALL_USERS "SELECT USERNAME FROM USERS"
#define GET_USER_SCORE "SELECT SCORE FROM USERS WHERE USERNAME = ?;"