#pragma once
#define CREATE_USERS_TABLE "CREATE TABLE IF NOT EXISTS USERS (USER_ID INTEGER PRIMARY KEY AUTOINCREMENT, USERNAME TEXT NOT NULL UNIQUE, PASSWORD TEXT NOT NULL, EMAIL TEXT NOT NULL UNIQUE);"
#define ADD_NEW_USER "INSERT INTO USERS (USERNAME, PASSWORD, EMAIL) VALUES (?, ?, ?);"
#define DELETE_EXISTING_USER "DELETE FROM USERS WHERE USERNAME = ?;"
#define UPDATE_PLAYER_PASSWORD "UPDATE USERS SET PASSWORD = ? WHERE USERNAME = ?;"
#define GET_ALL_USERS "SELECT USERNAME FROM USERS;"
#define VERIFY_USER "SELECT EXISTS(SELECT 1 FROM USERS WHERE USERNAME = ? AND PASSWORD = ? LIMIT 1);"
